name: 'Project context'
description: 'Query and update project context'
inputs:
  defaultBranch:
    description: 'Project default branch'
    required: false
    default: 'main'
  tagPrefix:
    description: 'Tag Prefix'
    required: false
    default: 'v'
  releaseBranchPrefix:
    description: 'Release branch Prefix'
    required: false
    default: 'release/'
  mergedReleaseMsgRegex:
    description: 'Merged release message regex'
    required: false
    default: '^Merge pull request #\d+ from .+/release/.+$'
  patterns:
    description: 'Project patterns to search/replace version. E.g: <glob_pattern_with_ext>::<regex_group>::<version_regex>'
    required: false
  allowCommit:
    description: 'Allow commit to fix version if not match'
    required: false
    default: 'true'
  allowTag:
    description: 'Allow tag in post script if merged release branch'
    required: false
    default: 'true'
  prefixCiMsg:
    description: 'Prefix bot message'
    required: false
    default: <ci-auto-commit>
  correctVerMsg:
    description: 'CI: Correct version message template'
    required: false
    default: Correct version
  releaseVerMsg:
    description: 'CI: Release version message template'
    required: false
    default: Release version
  dry:
    description: 'CI: Dry run'
    required: false
    default: 'true'
outputs:
  branch:
    description: 'Current branch name or tag name'
  onDefaultBranch:
    description: 'Check whether current event is on default branch or not'
  isPR:
    description: 'Check whether current event is on pull request or not'
  isReleasePR:
    description: 'Check whether current event is on release pull request or not'
  isMerged:
    description: 'Check whether current event is merged PR'
  isClosed:
    description: 'Check whether current event is close PR but not merged into target branch'
  isAfterMergedReleasePR:
    description: 'Check whether current event is a merged commit after merged release pull request into default branch or not'
  isTag:
    description: 'Check whether current event is on ref tag'
  commitMsg:
    description: 'Latest commit message'
  commitId:
    description: 'Latest commit id'
  version:
    description: 'Current tag version or release version. Null if not tag or release pull request'
  ci-mustFixVersion:
    description: 'CI: Need to fix version to match with release name'
  ci-needTag:
    description: 'CI: Need to tag new version if release branch is merged'
  ci-isPushed:
    description: 'CI: Check whether if auto commit is pushed to remote'
  ci-commitId:
    description: 'CI: auto commit id'
  ci-commitMsg:
    description: 'CI: auto commit message'
runs:
  using: 'node12'
  main: 'dist/index.js'